/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendingMachine;

import java.awt.Color;
import javax.swing.JOptionPane;
import static vendingMachine.work.Cstock;
import static vendingMachine.work.PQ;
import static vendingMachine.work.changeStock;
import static vendingMachine.work.machineMoney;
import static vendingMachine.work.moneyInMachine;

/**
 *
 * @author muhammadnouman
 */
public class Change extends javax.swing.JFrame {

    /**
     * Creates new form Change
     */
    public Change() {
        initComponents();
        //setting up the size of frame
        setSize(688, 823);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField50Note = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField20Note = new javax.swing.JTextField();
        jButtonCollect = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField10Note = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5Note = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2Coin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1coin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField50Cent = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField20Cent = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10Cent = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField5Cent = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField2cent = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField1cent = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/50eurorSmall.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 142, 150, 75);

        jTextField50Note.setEditable(false);
        getContentPane().add(jTextField50Note);
        jTextField50Note.setBounds(174, 169, 70, 26);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/euro20small-g.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 230, 150, 75);

        jTextField20Note.setEditable(false);
        getContentPane().add(jTextField20Note);
        jTextField20Note.setBounds(174, 264, 70, 26);

        jButtonCollect.setText("Collect");
        jButtonCollect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCollectActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCollect);
        jButtonCollect.setBounds(519, 725, 116, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/euro010small.jpeg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(6, 323, 150, 75);

        jTextField10Note.setEditable(false);
        getContentPane().add(jTextField10Note);
        jTextField10Note.setBounds(174, 344, 70, 26);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/5eurosmall.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(6, 416, 150, 75);

        jTextField5Note.setEditable(false);
        jTextField5Note.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5NoteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5Note);
        jTextField5Note.setBounds(174, 437, 70, 26);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/2small.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(449, 136, 90, 81);

        jTextField2Coin.setEditable(false);
        getContentPane().add(jTextField2Coin);
        jTextField2Coin.setBounds(587, 154, 70, 26);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/1eurocoin.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(449, 224, 90, 81);

        jTextField1coin.setEditable(false);
        getContentPane().add(jTextField1coin);
        jTextField1coin.setBounds(587, 246, 70, 26);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/50cent.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(449, 313, 90, 81);

        jTextField50Cent.setEditable(false);
        getContentPane().add(jTextField50Cent);
        jTextField50Cent.setBounds(587, 337, 70, 26);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/20cent.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(449, 408, 90, 81);

        jTextField20Cent.setEditable(false);
        getContentPane().add(jTextField20Cent);
        jTextField20Cent.setBounds(587, 436, 70, 26);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/10cent.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 509, 90, 81);

        jTextField10Cent.setEditable(false);
        getContentPane().add(jTextField10Cent);
        jTextField10Cent.setBounds(174, 533, 70, 26);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/5cent.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(449, 507, 90, 81);

        jTextField5Cent.setEditable(false);
        getContentPane().add(jTextField5Cent);
        jTextField5Cent.setBounds(587, 538, 70, 26);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/2centcoin.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 626, 90, 81);

        jTextField2cent.setEditable(false);
        getContentPane().add(jTextField2cent);
        jTextField2cent.setBounds(174, 649, 70, 26);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/1centcoin.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(449, 626, 78, 81);

        jTextField1cent.setEditable(false);
        getContentPane().add(jTextField1cent);
        jTextField1cent.setBounds(587, 651, 70, 26);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(684, 105));

        jLabel1.setBackground(new java.awt.Color(102, 255, 204));
        jLabel1.setFont(new java.awt.Font("Beirut", 1, 24)); // NOI18N
        jLabel1.setText("Collect Your Change:");

        jLabel15.setText("Money in machine:");

        jLabel16.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(88, 88, 88)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 684, 105);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/chang.jpg"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 106, 690, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //when window gains focus populate all the text fields under the formWindowGainedFocus
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        jTextField50Note.setText(Integer.toString(changeStock[0]));
        jTextField20Note.setText(Integer.toString(changeStock[1]));
        jTextField10Note.setText(Integer.toString(changeStock[2]));
        jTextField5Note.setText(Integer.toString(changeStock[3]));
        jTextField2Coin.setText(Integer.toString(changeStock[4]));
        jTextField1coin.setText(Integer.toString(changeStock[5]));
        jTextField50Cent.setText(Integer.toString(changeStock[6]));
        jTextField20Cent.setText(Integer.toString(changeStock[7]));
        jTextField10Cent.setText(Integer.toString(changeStock[8]));
        jTextField5Cent.setText(Integer.toString(changeStock[9]));
        jTextField2cent.setText(Integer.toString(changeStock[10]));
        jTextField1cent.setText(Integer.toString(changeStock[11]));
        jLabel16.setText("€" + Double.toString(Math.round(moneyInMachine(machineMoney) * 100) / 100.0));
        //setting up if statements 
        //if specific type of change is equal to zero jTextfield stays red
        //otherwise turns into green colour
        if (changeStock[0] > 0) {
            jTextField50Note.setBackground(Color.green);
        } else {
            jTextField50Note.setBackground(Color.red);
        }
        if (changeStock[1] > 0) {
            jTextField20Note.setBackground(Color.green);
        } else {
            jTextField20Note.setBackground(Color.red);
        }
        if (changeStock[2] > 0) {
            jTextField10Note.setBackground(Color.green);
        } else {
            jTextField10Note.setBackground(Color.red);
        }
        if (changeStock[3] > 0) {
            jTextField5Note.setBackground(Color.green);
        } else {
            jTextField5Note.setBackground(Color.red);
        }
        if (changeStock[4] > 0) {
            jTextField2Coin.setBackground(Color.green);
        } else {
            jTextField2Coin.setBackground(Color.red);
        }
        if (changeStock[5] > 0) {
            jTextField1coin.setBackground(Color.green);
        } else {
            jTextField1coin.setBackground(Color.red);
        }
        if (changeStock[6] > 0) {
            jTextField50Cent.setBackground(Color.green);
        } else {
            jTextField50Cent.setBackground(Color.red);
        }
        if (changeStock[7] > 0) {
            jTextField20Cent.setBackground(Color.green);
        } else {
            jTextField20Cent.setBackground(Color.red);
        }
        if (changeStock[8] > 0) {
            jTextField10Cent.setBackground(Color.green);
        } else {
            jTextField10Cent.setBackground(Color.red);
        }
        if (changeStock[9] > 0) {
            jTextField5Cent.setBackground(Color.green);
        } else {
            jTextField5Cent.setBackground(Color.red);
        }
        if (changeStock[10] > 0) {
            jTextField2cent.setBackground(Color.green);
        } else {
            jTextField2cent.setBackground(Color.red);
        }
        if (changeStock[11] > 0) {
            jTextField1cent.setBackground(Color.green);
        } else {
            jTextField1cent.setBackground(Color.red);
        }
    }//GEN-LAST:event_formWindowGainedFocus
    //calling different methods from class work
    private void jButtonCollectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCollectActionPerformed
        JOptionPane.showMessageDialog(null, "Have A Nive Day !!!");
        Cstock();
        PQ();
        CustomerDetails cd = new CustomerDetails();
        cd.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCollectActionPerformed

    private void jTextField5NoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5NoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5NoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Change().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCollect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField10Cent;
    private javax.swing.JTextField jTextField10Note;
    private javax.swing.JTextField jTextField1cent;
    private javax.swing.JTextField jTextField1coin;
    private javax.swing.JTextField jTextField20Cent;
    private javax.swing.JTextField jTextField20Note;
    private javax.swing.JTextField jTextField2Coin;
    private javax.swing.JTextField jTextField2cent;
    private javax.swing.JTextField jTextField50Cent;
    private javax.swing.JTextField jTextField50Note;
    private javax.swing.JTextField jTextField5Cent;
    private javax.swing.JTextField jTextField5Note;
    // End of variables declaration//GEN-END:variables
}
