/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendingMachine;

import javax.swing.JOptionPane;
import static vendingMachine.work.amountPaid;
import static vendingMachine.work.name;
import static vendingMachine.work.price;
import static vendingMachine.work.purchase;
import static vendingMachine.work.quantity;

/**
 *
 * @author muhammadnouman
 */
public class Desserts extends javax.swing.JFrame {

    /**
     * Creates new form Desserts
     */
    public Desserts() {
        initComponents();
        //setting up size of the frame
        setSize(1163, 840);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonCookies = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonBrownies = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonChocolateTDB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        list1 = new java.awt.List();
        jButtonIceCream = new javax.swing.JButton();
        jButtonPizzas = new javax.swing.JButton();
        jButtonCustomerFeedBack = new javax.swing.JButton();
        jButtonOtherItems = new javax.swing.JButton();
        jButtonRefund = new javax.swing.JButton();
        jButtonExitOrder = new javax.swing.JButton();
        jTextFieldTotalPurchase = new javax.swing.JTextField();
        jButtonWrapUp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Desserts Range");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("You Have Selected:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 149, 180, 50);

        jButtonCookies.setBackground(new java.awt.Color(204, 153, 255));
        jButtonCookies.setText("Cookies");
        jButtonCookies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCookiesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCookies);
        jButtonCookies.setBounds(385, 209, 390, 70);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Raanana", 1, 24)); // NOI18N
        jLabel1.setText("Desserts Range");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 910, 120);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1160, 125);

        jButtonBrownies.setBackground(new java.awt.Color(0, 204, 204));
        jButtonBrownies.setText("Brownies");
        jButtonBrownies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowniesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBrownies);
        jButtonBrownies.setBounds(385, 359, 390, 70);

        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Total Amount:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 713, 90, 16);

        jButtonChocolateTDB.setBackground(new java.awt.Color(204, 153, 255));
        jButtonChocolateTDB.setText("Chocolate TDB");
        jButtonChocolateTDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChocolateTDBActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonChocolateTDB);
        jButtonChocolateTDB.setBounds(385, 527, 390, 70);

        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Items:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(294, 166, 208, 16);

        list1.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(list1);
        list1.setBounds(20, 209, 260, 450);

        jButtonIceCream.setBackground(new java.awt.Color(0, 204, 204));
        jButtonIceCream.setText("Ice Cream");
        jButtonIceCream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIceCreamActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIceCream);
        jButtonIceCream.setBounds(385, 687, 390, 70);

        jButtonPizzas.setBackground(new java.awt.Color(255, 102, 255));
        jButtonPizzas.setText("Pizzas");
        jButtonPizzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPizzasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPizzas);
        jButtonPizzas.setBounds(919, 345, 194, 98);

        jButtonCustomerFeedBack.setBackground(new java.awt.Color(204, 255, 0));
        jButtonCustomerFeedBack.setText("Customer's Feed Back");
        jButtonCustomerFeedBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerFeedBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCustomerFeedBack);
        jButtonCustomerFeedBack.setBounds(919, 235, 194, 98);

        jButtonOtherItems.setBackground(new java.awt.Color(255, 204, 204));
        jButtonOtherItems.setText("Other Items");
        jButtonOtherItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtherItemsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOtherItems);
        jButtonOtherItems.setBounds(919, 455, 194, 98);

        jButtonRefund.setBackground(new java.awt.Color(255, 51, 51));
        jButtonRefund.setText("Refund/Cancel");
        jButtonRefund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefundActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRefund);
        jButtonRefund.setBounds(919, 571, 194, 98);

        jButtonExitOrder.setBackground(new java.awt.Color(255, 51, 51));
        jButtonExitOrder.setText("Exit Order");
        jButtonExitOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitOrderActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExitOrder);
        jButtonExitOrder.setBounds(919, 131, 194, 98);

        jTextFieldTotalPurchase.setEditable(false);
        getContentPane().add(jTextFieldTotalPurchase);
        jTextFieldTotalPurchase.setBounds(128, 708, 152, 26);

        jButtonWrapUp.setBackground(new java.awt.Color(0, 0, 255));
        jButtonWrapUp.setText("Wrap Up");
        jButtonWrapUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWrapUpActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonWrapUp);
        jButtonWrapUp.setBounds(919, 687, 194, 98);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/desserts.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 126, 1160, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //calling different method from class work and assingn these as a value to different action performed of nutton
    private void jButtonChocolateTDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChocolateTDBActionPerformed
        quantity[7][2] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[7][2], quantity[7][2], price[7][2], 7, 2);
    }//GEN-LAST:event_jButtonChocolateTDBActionPerformed
    //setting up objects of different frames and assign them as a value to different buttons
    private void jButtonPizzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPizzasActionPerformed
        PizzaRange pizza = new PizzaRange();
        pizza.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonPizzasActionPerformed

    private void jButtonCustomerFeedBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerFeedBackActionPerformed
        CustomerDetails cd = new CustomerDetails();
        cd.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCustomerFeedBackActionPerformed

    private void jButtonOtherItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtherItemsActionPerformed
        OtherItems oi = new OtherItems();
        oi.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonOtherItemsActionPerformed
    //calling a method money from class work to perform the refund action
    private void jButtonRefundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefundActionPerformed
        amountPaid = amountPaid + purchase;
        while (amountPaid > 0) {
            vendingMachine.work.money();
        }
        vendingMachine.work.refund();
        Change c = new Change();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRefundActionPerformed

    private void jButtonExitOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitOrderActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonExitOrderActionPerformed

    private void jButtonWrapUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWrapUpActionPerformed
        //if purchase amount is 0 give message otherwise give back change
        if (purchase == 0) {
            JOptionPane.showMessageDialog(null, "To Proceed Purchase amount has to be over €0.0");
        } else {
            while (amountPaid > 0) {
                vendingMachine.work.money();
            }
            Change c = new Change();
            c.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButtonWrapUpActionPerformed

    private void jButtonCookiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCookiesActionPerformed
        quantity[7][0] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[7][0], quantity[7][0], price[7][0], 7, 0);
    }//GEN-LAST:event_jButtonCookiesActionPerformed

    private void jButtonBrowniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowniesActionPerformed
        quantity[7][1] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[7][1], quantity[7][1], price[7][1], 7, 1);
    }//GEN-LAST:event_jButtonBrowniesActionPerformed

    private void jButtonIceCreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIceCreamActionPerformed
        quantity[7][3] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[7][3], quantity[7][3], price[7][3], 7, 3);
    }//GEN-LAST:event_jButtonIceCreamActionPerformed
    //when window gains focus is populate the text fields under the formWindowGainedFocus 
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        jTextFieldTotalPurchase.setText(Double.toString(purchase));
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desserts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrownies;
    private javax.swing.JButton jButtonChocolateTDB;
    private javax.swing.JButton jButtonCookies;
    private javax.swing.JButton jButtonCustomerFeedBack;
    private javax.swing.JButton jButtonExitOrder;
    private javax.swing.JButton jButtonIceCream;
    private javax.swing.JButton jButtonOtherItems;
    private javax.swing.JButton jButtonPizzas;
    private javax.swing.JButton jButtonRefund;
    private javax.swing.JButton jButtonWrapUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldTotalPurchase;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
