/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendingMachine;

import javax.swing.JOptionPane;
import static vendingMachine.work.amountPaid;
import static vendingMachine.work.name;
import static vendingMachine.work.price;
import static vendingMachine.work.purchase;
import static vendingMachine.work.quantity;

/**
 *
 * @author muhammadnouman
 */
public class Dips extends javax.swing.JFrame {

    /**
     * Creates new form Dips
     */
    public Dips() {
        initComponents();
        //setting up size of the frame
        setSize(1128, 832);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBbqDip25gm = new javax.swing.JButton();
        jButtonGarlicDip25gm = new javax.swing.JButton();
        jButtonSweetChilli25gm = new javax.swing.JButton();
        jButtonHoneyMusterd25gm = new javax.swing.JButton();
        jButtonHot25gm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        list1 = new java.awt.List();
        jButtonGarlic100gm = new javax.swing.JButton();
        jButtonBbq100gm = new javax.swing.JButton();
        jButtonHot100gm = new javax.swing.JButton();
        jButtonPizzas = new javax.swing.JButton();
        jButtonCustomerFeedBack = new javax.swing.JButton();
        jButtonOtherItems = new javax.swing.JButton();
        jButtonRefundCancel = new javax.swing.JButton();
        jButtonExitOrder = new javax.swing.JButton();
        jButtonWrapUp = new javax.swing.JButton();
        jTextFieldTotalPurchase = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dips Range");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jButtonBbqDip25gm.setBackground(new java.awt.Color(153, 153, 153));
        jButtonBbqDip25gm.setText("BBQ 25gm");
        jButtonBbqDip25gm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBbqDip25gmActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBbqDip25gm);
        jButtonBbqDip25gm.setBounds(385, 203, 165, 70);

        jButtonGarlicDip25gm.setBackground(new java.awt.Color(255, 255, 204));
        jButtonGarlicDip25gm.setText("Garlic 25gm");
        jButtonGarlicDip25gm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGarlicDip25gmActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGarlicDip25gm);
        jButtonGarlicDip25gm.setBounds(640, 203, 164, 70);

        jButtonSweetChilli25gm.setBackground(new java.awt.Color(255, 255, 204));
        jButtonSweetChilli25gm.setText("Sweet Chilli 25gm");
        jButtonSweetChilli25gm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSweetChilli25gmActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSweetChilli25gm);
        jButtonSweetChilli25gm.setBounds(385, 364, 165, 70);

        jButtonHoneyMusterd25gm.setBackground(new java.awt.Color(153, 255, 204));
        jButtonHoneyMusterd25gm.setText("Honey Musterd 25gm");
        jButtonHoneyMusterd25gm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHoneyMusterd25gmActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHoneyMusterd25gm);
        jButtonHoneyMusterd25gm.setBounds(640, 364, 164, 70);

        jButtonHot25gm.setBackground(new java.awt.Color(255, 255, 204));
        jButtonHot25gm.setText("Frank's Hot 25gm");
        jButtonHot25gm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHot25gmActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHot25gm);
        jButtonHot25gm.setBounds(385, 540, 165, 70);

        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("You Have Selected:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 137, 180, 16);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Raanana", 1, 24)); // NOI18N
        jLabel1.setText("Dips Range");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1130, 120);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1130, 125);

        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Total Amount:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 719, 90, 16);

        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Items:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(385, 137, 208, 16);

        list1.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(list1);
        list1.setBounds(20, 163, 260, 478);

        jButtonGarlic100gm.setBackground(new java.awt.Color(153, 255, 204));
        jButtonGarlic100gm.setText("Garlic 100gm");
        jButtonGarlic100gm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGarlic100gmActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGarlic100gm);
        jButtonGarlic100gm.setBounds(640, 540, 164, 70);

        jButtonBbq100gm.setBackground(new java.awt.Color(153, 255, 204));
        jButtonBbq100gm.setText("BBQ 100gm");
        jButtonBbq100gm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBbq100gmActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBbq100gm);
        jButtonBbq100gm.setBounds(385, 692, 165, 72);

        jButtonHot100gm.setBackground(new java.awt.Color(153, 153, 153));
        jButtonHot100gm.setText("Frank's Hot 100gm");
        jButtonHot100gm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHot100gmActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHot100gm);
        jButtonHot100gm.setBounds(640, 692, 164, 72);

        jButtonPizzas.setBackground(new java.awt.Color(255, 102, 255));
        jButtonPizzas.setText("Pizzas");
        jButtonPizzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPizzasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPizzas);
        jButtonPizzas.setBounds(903, 351, 194, 98);

        jButtonCustomerFeedBack.setBackground(new java.awt.Color(204, 255, 0));
        jButtonCustomerFeedBack.setText("Customer's Feed Back");
        jButtonCustomerFeedBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerFeedBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCustomerFeedBack);
        jButtonCustomerFeedBack.setBounds(903, 241, 194, 98);

        jButtonOtherItems.setBackground(new java.awt.Color(255, 204, 204));
        jButtonOtherItems.setText("Other Items");
        jButtonOtherItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtherItemsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOtherItems);
        jButtonOtherItems.setBounds(903, 461, 194, 98);

        jButtonRefundCancel.setBackground(new java.awt.Color(255, 51, 51));
        jButtonRefundCancel.setText("Refund/Cancel");
        jButtonRefundCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefundCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRefundCancel);
        jButtonRefundCancel.setBounds(903, 577, 194, 98);

        jButtonExitOrder.setBackground(new java.awt.Color(255, 51, 51));
        jButtonExitOrder.setText("Exit Order");
        jButtonExitOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitOrderActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExitOrder);
        jButtonExitOrder.setBounds(903, 137, 194, 98);

        jButtonWrapUp.setBackground(new java.awt.Color(0, 0, 255));
        jButtonWrapUp.setText("Wrap Up");
        jButtonWrapUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWrapUpActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonWrapUp);
        jButtonWrapUp.setBounds(903, 693, 194, 98);

        jTextFieldTotalPurchase.setEditable(false);
        getContentPane().add(jTextFieldTotalPurchase);
        jTextFieldTotalPurchase.setBounds(122, 714, 158, 26);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/dips.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 126, 1130, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //setting up objects of different frames and call them under different buttons
    private void jButtonPizzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPizzasActionPerformed
        PizzaRange pizza = new PizzaRange();
        pizza.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonPizzasActionPerformed

    private void jButtonCustomerFeedBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerFeedBackActionPerformed
        CustomerDetails cd = new CustomerDetails();
        cd.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCustomerFeedBackActionPerformed

    private void jButtonOtherItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtherItemsActionPerformed
        OtherItems oi = new OtherItems();
        oi.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonOtherItemsActionPerformed
    //calling a method money from class work to perform the refund action
    private void jButtonRefundCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefundCancelActionPerformed
        amountPaid = amountPaid + purchase;
        while (amountPaid > 0) {
            vendingMachine.work.money();
        }
        vendingMachine.work.refund();
        Change c = new Change();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRefundCancelActionPerformed

    private void jButtonExitOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitOrderActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonExitOrderActionPerformed

    private void jButtonWrapUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWrapUpActionPerformed
        //if purchase amount is 0 give message otherwise give back change
        if (purchase == 0) {
            JOptionPane.showMessageDialog(null, "To Proceed Purchase amount has to be over €0.0");
        } else {
            while (amountPaid > 0) {
                vendingMachine.work.money();
            }
            Change c = new Change();
            c.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButtonWrapUpActionPerformed
    //calling different methods from class work and place them under different buttons
    private void jButtonBbqDip25gmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBbqDip25gmActionPerformed
        quantity[5][0] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[5][0], quantity[5][0], price[5][0], 5, 0);
    }//GEN-LAST:event_jButtonBbqDip25gmActionPerformed

    private void jButtonGarlicDip25gmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGarlicDip25gmActionPerformed
        quantity[5][1] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[5][1], quantity[5][1], price[5][1], 5, 1);
    }//GEN-LAST:event_jButtonGarlicDip25gmActionPerformed

    private void jButtonSweetChilli25gmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSweetChilli25gmActionPerformed
        quantity[5][2] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[5][2], quantity[5][2], price[5][2], 5, 2);
    }//GEN-LAST:event_jButtonSweetChilli25gmActionPerformed

    private void jButtonHoneyMusterd25gmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHoneyMusterd25gmActionPerformed
        quantity[5][3] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[5][3], quantity[5][3], price[5][3], 5, 3);
    }//GEN-LAST:event_jButtonHoneyMusterd25gmActionPerformed

    private void jButtonHot25gmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHot25gmActionPerformed
        quantity[5][4] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[5][4], quantity[5][4], price[5][4], 5, 4);
    }//GEN-LAST:event_jButtonHot25gmActionPerformed

    private void jButtonGarlic100gmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGarlic100gmActionPerformed
        quantity[5][5] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[5][5], quantity[5][5], price[5][5], 5, 5);
    }//GEN-LAST:event_jButtonGarlic100gmActionPerformed

    private void jButtonBbq100gmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBbq100gmActionPerformed
        quantity[5][6] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[5][6], quantity[5][6], price[5][6], 5, 6);
    }//GEN-LAST:event_jButtonBbq100gmActionPerformed

    private void jButtonHot100gmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHot100gmActionPerformed
        quantity[5][7] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[5][7], quantity[5][7], price[5][7], 5, 7);
    }//GEN-LAST:event_jButtonHot100gmActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        jTextFieldTotalPurchase.setText(Double.toString(purchase));
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dips().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBbq100gm;
    private javax.swing.JButton jButtonBbqDip25gm;
    private javax.swing.JButton jButtonCustomerFeedBack;
    private javax.swing.JButton jButtonExitOrder;
    private javax.swing.JButton jButtonGarlic100gm;
    private javax.swing.JButton jButtonGarlicDip25gm;
    private javax.swing.JButton jButtonHoneyMusterd25gm;
    private javax.swing.JButton jButtonHot100gm;
    private javax.swing.JButton jButtonHot25gm;
    private javax.swing.JButton jButtonOtherItems;
    private javax.swing.JButton jButtonPizzas;
    private javax.swing.JButton jButtonRefundCancel;
    private javax.swing.JButton jButtonSweetChilli25gm;
    private javax.swing.JButton jButtonWrapUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldTotalPurchase;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
