/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendingMachine;

import javax.swing.JOptionPane;
import static vendingMachine.work.amountPaid;
import static vendingMachine.work.purchase;

/**
 *
 * @author muhammadnouman
 */
public class OtherItems extends javax.swing.JFrame {

    /**
     * Creates new form OtherItems
     */
    public OtherItems() {
        initComponents();
        //setting up frame size
        setSize(1148, 832);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextFieldTotalPurchase = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        list1 = new java.awt.List();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSides = new javax.swing.JButton();
        jButtonChickenItems = new javax.swing.JButton();
        jButtonSesserts = new javax.swing.JButton();
        jButtonDips = new javax.swing.JButton();
        jButtonWrapUp = new javax.swing.JButton();
        jButtonExitOrder = new javax.swing.JButton();
        jButtonPizzas = new javax.swing.JButton();
        jButtonCustomerFeedBack = new javax.swing.JButton();
        jButtonOtherItems = new javax.swing.JButton();
        jButtonRefundCancel = new javax.swing.JButton();
        jButtonDrinks = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Other Items");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Total Amount:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 740, 90, 16);

        jTextFieldTotalPurchase.setEditable(false);
        getContentPane().add(jTextFieldTotalPurchase);
        jTextFieldTotalPurchase.setBounds(110, 730, 156, 26);

        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("You Have Selected:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 148, 180, 50);

        list1.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(list1);
        list1.setBounds(10, 208, 260, 473);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        jLabel1.setText("Other Items");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1030, 130);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1150, 140);

        jButtonSides.setBackground(new java.awt.Color(102, 102, 255));
        jButtonSides.setText("Sides");
        jButtonSides.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSidesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSides);
        jButtonSides.setBounds(396, 326, 396, 88);

        jButtonChickenItems.setBackground(new java.awt.Color(255, 102, 102));
        jButtonChickenItems.setText("Chicken Items");
        jButtonChickenItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChickenItemsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonChickenItems);
        jButtonChickenItems.setBounds(396, 208, 396, 88);

        jButtonSesserts.setBackground(new java.awt.Color(204, 204, 0));
        jButtonSesserts.setText("Desserts");
        jButtonSesserts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSessertsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSesserts);
        jButtonSesserts.setBounds(396, 560, 396, 88);

        jButtonDips.setBackground(new java.awt.Color(255, 102, 102));
        jButtonDips.setText("Dips");
        jButtonDips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDipsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDips);
        jButtonDips.setBounds(396, 439, 396, 88);

        jButtonWrapUp.setBackground(new java.awt.Color(0, 0, 255));
        jButtonWrapUp.setText("Wrap Up");
        jButtonWrapUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWrapUpActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonWrapUp);
        jButtonWrapUp.setBounds(918, 697, 194, 98);

        jButtonExitOrder.setBackground(new java.awt.Color(255, 51, 51));
        jButtonExitOrder.setText("Exit Order");
        jButtonExitOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitOrderActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExitOrder);
        jButtonExitOrder.setBounds(918, 148, 194, 98);

        jButtonPizzas.setBackground(new java.awt.Color(255, 102, 255));
        jButtonPizzas.setText("Pizzas");
        jButtonPizzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPizzasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPizzas);
        jButtonPizzas.setBounds(918, 362, 194, 98);

        jButtonCustomerFeedBack.setBackground(new java.awt.Color(204, 255, 0));
        jButtonCustomerFeedBack.setText("Customer's Feed Back");
        jButtonCustomerFeedBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerFeedBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCustomerFeedBack);
        jButtonCustomerFeedBack.setBounds(918, 252, 194, 98);

        jButtonOtherItems.setBackground(new java.awt.Color(255, 204, 204));
        jButtonOtherItems.setText("Other Items");
        jButtonOtherItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtherItemsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOtherItems);
        jButtonOtherItems.setBounds(918, 471, 194, 98);

        jButtonRefundCancel.setBackground(new java.awt.Color(255, 51, 51));
        jButtonRefundCancel.setText("Refund/Cancel");
        jButtonRefundCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefundCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRefundCancel);
        jButtonRefundCancel.setBounds(918, 581, 194, 98);

        jButtonDrinks.setBackground(new java.awt.Color(255, 255, 153));
        jButtonDrinks.setText("Drinks");
        jButtonDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrinksActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDrinks);
        jButtonDrinks.setBounds(396, 686, 396, 88);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/otherItems.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 136, 1150, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //setting up objects of different frames and assign them as value to different buttons
    private void jButtonChickenItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChickenItemsActionPerformed
        ChickenItems ci = new ChickenItems();
        ci.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonChickenItemsActionPerformed

    private void jButtonWrapUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWrapUpActionPerformed
        //if purchase amount is 0 give message otherwise give back change
        if (purchase == 0) {
            JOptionPane.showMessageDialog(null, "To Proceed Purchase amount has to be over €0.0");
        } else {
            while (amountPaid > 0) {
                vendingMachine.work.money();
            }
            Change c = new Change();
            c.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButtonWrapUpActionPerformed

    private void jButtonExitOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitOrderActionPerformed
        //close the frame
        dispose();
    }//GEN-LAST:event_jButtonExitOrderActionPerformed

    private void jButtonPizzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPizzasActionPerformed
        PizzaRange pizza = new PizzaRange();
        pizza.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonPizzasActionPerformed

    private void jButtonCustomerFeedBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerFeedBackActionPerformed
        CustomerDetails cd = new CustomerDetails();
        cd.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCustomerFeedBackActionPerformed

    private void jButtonOtherItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtherItemsActionPerformed
        OtherItems oi = new OtherItems();
        oi.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonOtherItemsActionPerformed
    //calling a method money from class work to perform the refund action
    private void jButtonRefundCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefundCancelActionPerformed
        amountPaid = amountPaid + purchase;
        while (amountPaid > 0) {
            vendingMachine.work.money();
        }
        vendingMachine.work.refund();
        Change c = new Change();
        c.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButtonRefundCancelActionPerformed

    private void jButtonSidesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSidesActionPerformed
        Sides s = new Sides();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonSidesActionPerformed

    private void jButtonDipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDipsActionPerformed
        Dips d = new Dips();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonDipsActionPerformed

    private void jButtonSessertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSessertsActionPerformed
        Desserts d = new Desserts();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonSessertsActionPerformed

    private void jButtonDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrinksActionPerformed
        Drinks d = new Drinks();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonDrinksActionPerformed
    //whenever window gains focus populate the jTextField with total amount of purchase
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        jTextFieldTotalPurchase.setText(Double.toString(purchase));
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtherItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtherItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtherItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtherItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OtherItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChickenItems;
    private javax.swing.JButton jButtonCustomerFeedBack;
    private javax.swing.JButton jButtonDips;
    private javax.swing.JButton jButtonDrinks;
    private javax.swing.JButton jButtonExitOrder;
    private javax.swing.JButton jButtonOtherItems;
    private javax.swing.JButton jButtonPizzas;
    private javax.swing.JButton jButtonRefundCancel;
    private javax.swing.JButton jButtonSesserts;
    private javax.swing.JButton jButtonSides;
    private javax.swing.JButton jButtonWrapUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldTotalPurchase;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
