/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendingMachine;

import static vendingMachine.work.amountPaid;
import static vendingMachine.work.machineMoney;
import static vendingMachine.work.moneyInMachine;
import static vendingMachine.work.moneyStock;

/**
 *
 * @author muhammadnouman
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        //setting up size of the frame
        setSize(1168, 823);
    }

    //double amountDue=vendingMachine.PizzaChoice.totalPurchase+vendingMachine.MediumPizzaChoice.totalPurchase;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonContinueShopping = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton20Euro = new javax.swing.JButton();
        jButton10euro = new javax.swing.JButton();
        jButton5Note = new javax.swing.JButton();
        jButton2Coin = new javax.swing.JButton();
        jButton1coin = new javax.swing.JButton();
        jButton50Cent = new javax.swing.JButton();
        jButton20cent = new javax.swing.JButton();
        jButton10cent = new javax.swing.JButton();
        jButton5cent = new javax.swing.JButton();
        jButton2cent = new javax.swing.JButton();
        jButton1cent = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insert Money");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jButtonContinueShopping.setBackground(new java.awt.Color(0, 255, 0));
        jButtonContinueShopping.setText("Continue >>>");
        jButtonContinueShopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinueShoppingActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonContinueShopping);
        jButtonContinueShopping.setBounds(956, 168, 194, 98);

        jButton50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/50large.jpg"))); // NOI18N
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton50);
        jButton50.setBounds(38, 168, 335, 187);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1170, 115));

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel1.setText("Money Range");
        jLabel1.setPreferredSize(new java.awt.Dimension(1149, 115));

        jLabel2.setText("Total Money in Machine:");

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1170, 115);

        jButton20Euro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/20large.jpg"))); // NOI18N
        jButton20Euro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20EuroActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20Euro);
        jButton20Euro.setBounds(603, 168, 335, 187);

        jButton10euro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/10eurolarge.jpg"))); // NOI18N
        jButton10euro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10euroActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10euro);
        jButton10euro.setBounds(38, 450, 335, 187);

        jButton5Note.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/5large.png"))); // NOI18N
        jButton5Note.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5NoteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5Note);
        jButton5Note.setBounds(603, 450, 335, 187);

        jButton2Coin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/2small.png"))); // NOI18N
        jButton2Coin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CoinActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2Coin);
        jButton2Coin.setBounds(38, 643, 95, 93);

        jButton1coin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/1eurocoin.png"))); // NOI18N
        jButton1coin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1coinActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1coin);
        jButton1coin.setBounds(151, 643, 96, 93);

        jButton50Cent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/50cent.png"))); // NOI18N
        jButton50Cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50CentActionPerformed(evt);
            }
        });
        getContentPane().add(jButton50Cent);
        jButton50Cent.setBounds(265, 643, 98, 93);

        jButton20cent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/20cent.png"))); // NOI18N
        jButton20cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20centActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20cent);
        jButton20cent.setBounds(381, 643, 96, 93);

        jButton10cent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/10cent.png"))); // NOI18N
        jButton10cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10centActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10cent);
        jButton10cent.setBounds(495, 643, 97, 93);

        jButton5cent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/5cent.png"))); // NOI18N
        jButton5cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5centActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5cent);
        jButton5cent.setBounds(610, 643, 96, 93);

        jButton2cent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/2centcoin.png"))); // NOI18N
        jButton2cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2centActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2cent);
        jButton2cent.setBounds(724, 643, 96, 93);

        jButton1cent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/1centcoin.png"))); // NOI18N
        jButton1cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1centActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1cent);
        jButton1cent.setBounds(838, 643, 96, 93);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/money.jpeg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 116, 1170, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonContinueShoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinueShoppingActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonContinueShoppingActionPerformed
    //if action performs under any button then add that value to the amout paid and 
    //money stock increases of that type
    //Total amount in the machine increases and dispay in a jLabel
    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        amountPaid += 50.0;
        moneyStock[0]++;
        jLabel3.setText("€" + Double.toString(Math.round(moneyInMachine(machineMoney) * 100) / 100.0));
    }//GEN-LAST:event_jButton50ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        jLabel3.setText("€" + Double.toString(Math.round(moneyInMachine(machineMoney) * 100) / 100.0));
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton20EuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20EuroActionPerformed
        amountPaid += 20.0;
        moneyStock[1]++;
        jLabel3.setText("€" + Double.toString(Math.round(moneyInMachine(machineMoney) * 100) / 100.0));
    }//GEN-LAST:event_jButton20EuroActionPerformed

    private void jButton10euroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10euroActionPerformed
        amountPaid += 10.0;
        moneyStock[2]++;
        jLabel3.setText("€" + Double.toString(Math.round(moneyInMachine(machineMoney) * 100) / 100.0));
    }//GEN-LAST:event_jButton10euroActionPerformed

    private void jButton5NoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5NoteActionPerformed
        amountPaid += 5.0;
        moneyStock[3]++;
        jLabel3.setText("€" + Double.toString(Math.round(moneyInMachine(machineMoney) * 100) / 100.0));
    }//GEN-LAST:event_jButton5NoteActionPerformed

    private void jButton2CoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CoinActionPerformed
        amountPaid += 2.0;
        moneyStock[4]++;
        jLabel3.setText("€" + Double.toString(Math.round(moneyInMachine(machineMoney) * 100) / 100.0));
    }//GEN-LAST:event_jButton2CoinActionPerformed

    private void jButton1coinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1coinActionPerformed
        amountPaid += 1.0;
        moneyStock[5]++;
        jLabel3.setText("€" + Double.toString(Math.round(moneyInMachine(machineMoney) * 100) / 100.0));
    }//GEN-LAST:event_jButton1coinActionPerformed

    private void jButton50CentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50CentActionPerformed
        amountPaid += 0.50;
        moneyStock[6]++;
        jLabel3.setText("€" + Double.toString(Math.round(moneyInMachine(machineMoney) * 100) / 100.0));
    }//GEN-LAST:event_jButton50CentActionPerformed

    private void jButton20centActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20centActionPerformed
        amountPaid += 0.20;
        moneyStock[7]++;
        jLabel3.setText("€" + Double.toString(Math.round(moneyInMachine(machineMoney) * 100) / 100.0));
    }//GEN-LAST:event_jButton20centActionPerformed

    private void jButton1centActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1centActionPerformed
        amountPaid += 0.01;
        moneyStock[11]++;
        jLabel3.setText("€" + Double.toString(Math.round(moneyInMachine(machineMoney) * 100) / 100.0));
    }//GEN-LAST:event_jButton1centActionPerformed

    private void jButton10centActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10centActionPerformed
        amountPaid += 0.10;
        moneyStock[8]++;
        jLabel3.setText("€" + Double.toString(Math.round(moneyInMachine(machineMoney) * 100) / 100.0));
    }//GEN-LAST:event_jButton10centActionPerformed

    private void jButton5centActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5centActionPerformed
        amountPaid += 0.05;
        moneyStock[9]++;
        jLabel3.setText("€" + Double.toString(Math.round(moneyInMachine(machineMoney) * 100) / 100.0));
    }//GEN-LAST:event_jButton5centActionPerformed

    private void jButton2centActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2centActionPerformed
        amountPaid += 0.02;
        moneyStock[10]++;
        jLabel3.setText("€" + Double.toString(Math.round(moneyInMachine(machineMoney) * 100) / 100.0));
    }//GEN-LAST:event_jButton2centActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10cent;
    private javax.swing.JButton jButton10euro;
    private javax.swing.JButton jButton1cent;
    private javax.swing.JButton jButton1coin;
    private javax.swing.JButton jButton20Euro;
    private javax.swing.JButton jButton20cent;
    private javax.swing.JButton jButton2Coin;
    private javax.swing.JButton jButton2cent;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton50Cent;
    private javax.swing.JButton jButton5Note;
    private javax.swing.JButton jButton5cent;
    private javax.swing.JButton jButtonContinueShopping;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
