/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendingMachine;

import javax.swing.JOptionPane;
import static vendingMachine.work.amountPaid;
import static vendingMachine.work.name;
import static vendingMachine.work.price;
import static vendingMachine.work.purchase;
import static vendingMachine.work.quantity;

/**
 *
 * @author muhammadnouman
 */
public class PizzaRange extends javax.swing.JFrame {

    /**
     * Creates new form PizzaRange
     */
    public PizzaRange() {
        initComponents();
        //setting up size of frame
        setSize(1152, 840);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonExitOrder = new javax.swing.JButton();
        jButtonPizzas = new javax.swing.JButton();
        jButtonCustomerFeedBack = new javax.swing.JButton();
        jButtonOtherItems = new javax.swing.JButton();
        jButtonRefund = new javax.swing.JButton();
        jButtonWrapUp = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        list1 = new java.awt.List();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTotalPurchase = new javax.swing.JTextField();
        jRadioButtonLarge = new javax.swing.JRadioButton();
        jRadioButtonMedium = new javax.swing.JRadioButton();
        jRadioButtonSmall = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonCheeseAndTomato = new javax.swing.JButton();
        jButtonNewYorker = new javax.swing.JButton();
        jButtonItaliano = new javax.swing.JButton();
        jButtonVegiSupreme = new javax.swing.JButton();
        jButtonChickenFeast = new javax.swing.JButton();
        jButtonAmericanHot = new javax.swing.JButton();
        jButtonPeproni = new javax.swing.JButton();
        jButtonSizzler = new javax.swing.JButton();
        jButtonMeatilicious = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizzas Range");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jButtonExitOrder.setBackground(new java.awt.Color(255, 51, 51));
        jButtonExitOrder.setText("Exit Order");
        jButtonExitOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitOrderActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExitOrder);
        jButtonExitOrder.setBounds(944, 145, 194, 98);

        jButtonPizzas.setBackground(new java.awt.Color(255, 102, 255));
        jButtonPizzas.setText("Pizzas");
        jButtonPizzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPizzasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPizzas);
        jButtonPizzas.setBounds(944, 359, 194, 98);

        jButtonCustomerFeedBack.setBackground(new java.awt.Color(204, 255, 0));
        jButtonCustomerFeedBack.setText("Customer's Feed Back");
        jButtonCustomerFeedBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerFeedBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCustomerFeedBack);
        jButtonCustomerFeedBack.setBounds(944, 249, 194, 98);

        jButtonOtherItems.setBackground(new java.awt.Color(255, 204, 204));
        jButtonOtherItems.setText("Other Items");
        jButtonOtherItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtherItemsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOtherItems);
        jButtonOtherItems.setBounds(944, 468, 194, 98);

        jButtonRefund.setBackground(new java.awt.Color(255, 51, 51));
        jButtonRefund.setText("Refund/Cancel");
        jButtonRefund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefundActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRefund);
        jButtonRefund.setBounds(940, 580, 194, 98);

        jButtonWrapUp.setBackground(new java.awt.Color(0, 0, 255));
        jButtonWrapUp.setText("Wrap Up");
        jButtonWrapUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWrapUpActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonWrapUp);
        jButtonWrapUp.setBounds(940, 700, 194, 98);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        jLabel1.setText("Pizzas Range");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1140, 120);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1150, 127);

        list1.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(list1);
        list1.setBounds(10, 170, 238, 550);

        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Total Purchase :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 759, 100, 16);

        jTextFieldTotalPurchase.setEditable(false);
        getContentPane().add(jTextFieldTotalPurchase);
        jTextFieldTotalPurchase.setBounds(116, 754, 132, 26);

        buttonGroup1.add(jRadioButtonLarge);
        jRadioButtonLarge.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButtonLarge.setText("Large Pizza");
        getContentPane().add(jRadioButtonLarge);
        jRadioButtonLarge.setBounds(258, 169, 130, 23);

        buttonGroup1.add(jRadioButtonMedium);
        jRadioButtonMedium.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButtonMedium.setText("Medium Pizza");
        getContentPane().add(jRadioButtonMedium);
        jRadioButtonMedium.setBounds(494, 169, 130, 23);

        buttonGroup1.add(jRadioButtonSmall);
        jRadioButtonSmall.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButtonSmall.setText("Small Pizza");
        getContentPane().add(jRadioButtonSmall);
        jRadioButtonSmall.setBounds(723, 169, 130, 23);

        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Pizza Selection:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(266, 243, 97, 16);

        jButtonCheeseAndTomato.setBackground(new java.awt.Color(0, 153, 153));
        jButtonCheeseAndTomato.setText("Cheese & Tomato");
        jButtonCheeseAndTomato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheeseAndTomatoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCheeseAndTomato);
        jButtonCheeseAndTomato.setBounds(266, 298, 150, 70);

        jButtonNewYorker.setBackground(new java.awt.Color(204, 204, 0));
        jButtonNewYorker.setText("New Yorker");
        jButtonNewYorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewYorkerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNewYorker);
        jButtonNewYorker.setBounds(494, 298, 150, 70);

        jButtonItaliano.setBackground(new java.awt.Color(0, 102, 204));
        jButtonItaliano.setText("Italiano");
        jButtonItaliano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonItalianoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonItaliano);
        jButtonItaliano.setBounds(723, 298, 150, 70);

        jButtonVegiSupreme.setBackground(new java.awt.Color(204, 204, 0));
        jButtonVegiSupreme.setText("Vegi Supreme");
        jButtonVegiSupreme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVegiSupremeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVegiSupreme);
        jButtonVegiSupreme.setBounds(266, 498, 150, 70);

        jButtonChickenFeast.setBackground(new java.awt.Color(0, 102, 204));
        jButtonChickenFeast.setText("Chicken Feast");
        jButtonChickenFeast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChickenFeastActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonChickenFeast);
        jButtonChickenFeast.setBounds(494, 498, 150, 70);

        jButtonAmericanHot.setBackground(new java.awt.Color(204, 204, 0));
        jButtonAmericanHot.setText("American Hot");
        jButtonAmericanHot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAmericanHotActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAmericanHot);
        jButtonAmericanHot.setBounds(723, 498, 150, 70);

        jButtonPeproni.setBackground(new java.awt.Color(0, 102, 204));
        jButtonPeproni.setText("Peproni");
        jButtonPeproni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPeproniActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPeproni);
        jButtonPeproni.setBounds(266, 698, 150, 70);

        jButtonSizzler.setBackground(new java.awt.Color(204, 204, 0));
        jButtonSizzler.setText("Sizzler");
        jButtonSizzler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSizzlerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSizzler);
        jButtonSizzler.setBounds(494, 698, 150, 70);

        jButtonMeatilicious.setBackground(new java.awt.Color(0, 153, 153));
        jButtonMeatilicious.setText("Meatilicious");
        jButtonMeatilicious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMeatiliciousActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMeatilicious);
        jButtonMeatilicious.setBounds(723, 698, 150, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/images/Pizza.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 126, 1150, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitOrderActionPerformed
        //calling a method name dispose() which close the programme
        dispose();
    }//GEN-LAST:event_jButtonExitOrderActionPerformed
    //setting up objects of different frames and assign them as value to different buttons
    private void jButtonPizzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPizzasActionPerformed
        PizzaRange pizza = new PizzaRange();
        pizza.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonPizzasActionPerformed

    private void jButtonCustomerFeedBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerFeedBackActionPerformed
        CustomerDetails cd = new CustomerDetails();
        cd.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCustomerFeedBackActionPerformed

    private void jButtonOtherItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtherItemsActionPerformed
        OtherItems oi = new OtherItems();
        oi.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonOtherItemsActionPerformed

    private void jButtonRefundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefundActionPerformed
        //calling different methods to perform refund action
        amountPaid = amountPaid + purchase;
        //calling method from class work and runs untill the amount inserted inmachine is 0
        while (amountPaid > 0) {
            vendingMachine.work.money();
        }
        vendingMachine.work.refund();
        Change c = new Change();
        c.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButtonRefundActionPerformed

    private void jButtonWrapUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWrapUpActionPerformed
        //if purchase amount is 0 give message otherwise give back change
        if (purchase == 0) {
            JOptionPane.showMessageDialog(null, "To Proceed Purchase amount has to be over €0.0");
        } else {
            while (amountPaid > 0) {
                vendingMachine.work.money();
            }
            Change c = new Change();
            c.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButtonWrapUpActionPerformed
    //setting up if and else if statements,if jRadioButtonLarge is selected despence large item otherwise despence the product according
    //to the size selection
    private void jButtonCheeseAndTomatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheeseAndTomatoActionPerformed
        if (jRadioButtonLarge.isSelected()) {
            quantity[0][0] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[0][0], quantity[0][0], price[0][0], 0, 0);
        } else if (jRadioButtonMedium.isSelected()) {
            quantity[1][0] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[1][0], quantity[1][0], price[1][0], 1, 0);
        } else if (jRadioButtonSmall.isSelected()) {
            quantity[2][0] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[2][0], quantity[2][0], price[2][0], 2, 0);
        } else {
            JOptionPane.showMessageDialog(null, "Please select Pizza Size");
        }
    }//GEN-LAST:event_jButtonCheeseAndTomatoActionPerformed

    private void jButtonNewYorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewYorkerActionPerformed
        if (jRadioButtonLarge.isSelected()) {
            quantity[0][1] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[0][1], quantity[0][1], price[0][1], 0, 1);
        } else if (jRadioButtonMedium.isSelected()) {
            quantity[1][1] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[1][1], quantity[1][1], price[1][1], 1, 1);
        } else if (jRadioButtonSmall.isSelected()) {
            quantity[2][1] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[2][1], quantity[2][1], price[2][1], 2, 1);
        } else {
            JOptionPane.showMessageDialog(null, "Please select Pizza Size");
        }
    }//GEN-LAST:event_jButtonNewYorkerActionPerformed

    private void jButtonItalianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonItalianoActionPerformed
        if (jRadioButtonLarge.isSelected()) {
            quantity[0][2] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[0][2], quantity[0][2], price[0][2], 0, 2);
        } else if (jRadioButtonMedium.isSelected()) {
            quantity[1][2] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[1][2], quantity[1][2], price[1][2], 1, 2);
        } else if (jRadioButtonSmall.isSelected()) {
            quantity[2][2] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[2][2], quantity[2][2], price[2][2], 2, 2);
        } else {
            JOptionPane.showMessageDialog(null, "Please select Pizza Size");
        }
    }//GEN-LAST:event_jButtonItalianoActionPerformed

    private void jButtonVegiSupremeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVegiSupremeActionPerformed
        if (jRadioButtonLarge.isSelected()) {
            quantity[0][3] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[0][3], quantity[0][3], price[0][3], 0, 3);
        } else if (jRadioButtonMedium.isSelected()) {
            quantity[1][3] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[1][3], quantity[1][3], price[1][3], 1, 3);
        } else if (jRadioButtonSmall.isSelected()) {
            quantity[2][3] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[2][3], quantity[2][3], price[2][3], 2, 3);
        } else {
            JOptionPane.showMessageDialog(null, "Please select Pizza Size");
        }
    }//GEN-LAST:event_jButtonVegiSupremeActionPerformed

    private void jButtonChickenFeastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChickenFeastActionPerformed
        if (jRadioButtonLarge.isSelected()) {
            quantity[0][4] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[0][4], quantity[0][4], price[0][4], 0, 4);
        } else if (jRadioButtonMedium.isSelected()) {
            quantity[1][4] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[1][4], quantity[1][4], price[1][4], 1, 4);
        } else if (jRadioButtonSmall.isSelected()) {
            quantity[2][4] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[2][4], quantity[2][4], price[2][4], 2, 4);
        } else {
            JOptionPane.showMessageDialog(null, "Please select Pizza Size");
        }
    }//GEN-LAST:event_jButtonChickenFeastActionPerformed

    private void jButtonAmericanHotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmericanHotActionPerformed
        if (jRadioButtonLarge.isSelected()) {
            quantity[0][5] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[0][5], quantity[0][5], price[0][5], 0, 5);
        } else if (jRadioButtonMedium.isSelected()) {
            quantity[1][5] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[1][5], quantity[1][5], price[1][5], 1, 5);
        } else if (jRadioButtonSmall.isSelected()) {
            quantity[2][5] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[2][5], quantity[2][5], price[2][5], 2, 5);
        } else {
            JOptionPane.showMessageDialog(null, "Please select Pizza Size");
        }
    }//GEN-LAST:event_jButtonAmericanHotActionPerformed

    private void jButtonPeproniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeproniActionPerformed
        if (jRadioButtonLarge.isSelected()) {
            quantity[0][6] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[0][6], quantity[0][6], price[0][6], 0, 6);
        } else if (jRadioButtonMedium.isSelected()) {
            quantity[1][6] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[1][6], quantity[1][6], price[1][6], 1, 6);
        } else if (jRadioButtonSmall.isSelected()) {
            quantity[2][6] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[2][6], quantity[2][6], price[2][6], 2, 6);
        } else {
            JOptionPane.showMessageDialog(null, "Please select Pizza Size");
        }
    }//GEN-LAST:event_jButtonPeproniActionPerformed

    private void jButtonSizzlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSizzlerActionPerformed
        if (jRadioButtonLarge.isSelected()) {
            quantity[0][7] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[0][7], quantity[0][7], price[0][7], 0, 7);
        } else if (jRadioButtonMedium.isSelected()) {
            quantity[1][7] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[1][7], quantity[1][7], price[1][7], 1, 7);
        } else if (jRadioButtonSmall.isSelected()) {
            quantity[2][7] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[2][7], quantity[2][7], price[2][7], 2, 7);
        } else {
            JOptionPane.showMessageDialog(null, "Please select Pizza Size");
        }
    }//GEN-LAST:event_jButtonSizzlerActionPerformed

    private void jButtonMeatiliciousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMeatiliciousActionPerformed
        if (jRadioButtonLarge.isSelected()) {
            quantity[0][8] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[0][8], quantity[0][8], price[0][8], 0, 8);
        } else if (jRadioButtonMedium.isSelected()) {
            quantity[1][8] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[1][8], quantity[1][8], price[1][8], 1, 8);
        } else if (jRadioButtonSmall.isSelected()) {
            quantity[2][8] = vendingMachine.work.method(list1, jTextFieldTotalPurchase, name[2][8], quantity[2][8], price[2][8], 2, 8);
        } else {
            JOptionPane.showMessageDialog(null, "Please select Pizza Size");
        }
    }//GEN-LAST:event_jButtonMeatiliciousActionPerformed
    //whenever window gains focus populate the jTextField with total amount of purchase
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        jTextFieldTotalPurchase.setText(Double.toString(purchase));
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzaRange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzaRange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzaRange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzaRange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzaRange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAmericanHot;
    private javax.swing.JButton jButtonCheeseAndTomato;
    private javax.swing.JButton jButtonChickenFeast;
    private javax.swing.JButton jButtonCustomerFeedBack;
    private javax.swing.JButton jButtonExitOrder;
    private javax.swing.JButton jButtonItaliano;
    private javax.swing.JButton jButtonMeatilicious;
    private javax.swing.JButton jButtonNewYorker;
    private javax.swing.JButton jButtonOtherItems;
    private javax.swing.JButton jButtonPeproni;
    private javax.swing.JButton jButtonPizzas;
    private javax.swing.JButton jButtonRefund;
    private javax.swing.JButton jButtonSizzler;
    private javax.swing.JButton jButtonVegiSupreme;
    private javax.swing.JButton jButtonWrapUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonLarge;
    private javax.swing.JRadioButton jRadioButtonMedium;
    private javax.swing.JRadioButton jRadioButtonSmall;
    private javax.swing.JTextField jTextFieldTotalPurchase;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
